### ISSUE TITLE
BUGS ON AUTO NEXT / SKIP FIND ENEMY

### ISSUE THREAD

**Issue by idsystemku** [tinwaninja/Catur#1]
BUGS ON AUTO NEXT / SKIP FIND ENEMY 
there when a bot click that find next button the browser do reload and that make auto next not work please fix it

**Comment by tinwaninja** [comment]
If it gets stuck, please wait 2 minutes for the script to auto refresh or restart the engine

**Comment by tinwaninja** [comment]
If it gets stuck, please wait 2 minutes for the script to auto refresh or restart the engine, or alternatively if not using autostart
close firefox and re-run the python command in cmd
