### ISSUE TITLE
ERROR WHEN ENEMY ABORT THE GAME

### ISSUE THREAD

**Issue by SuryaMaulana** [tinwaninja/Catur#2]
![oie_transparent](https://user-images.githubusercontent.com/29894661/113232862-2e219780-92c8-11eb-8574-5565dcee7946.png)

**Comment by tinwaninja** [comment]
If it gets stuck, please wait 2 minutes for the script to auto refresh or restart the engine, or alternatively if not using autostart
close firefox and re-run the python command in cmd

**Comment by SuryaMaulana** [comment]
Thankyou
