### ISSUE TITLE
rapid mode bug

### ISSUE THREAD

**Issue by Abztrack** [tinwaninja/Catur#3]
tried rapid mode but in the second move it bugged, there's a red highlight in the board and the bot won't move, it just spams like this
![image](https://user-images.githubusercontent.com/23275372/113282790-9d6fa980-9311-11eb-8e54-f33609accf09.png)

**Comment by tinwaninja** [comment]
hello thanks for the report, for engine failure reading steps on rapid has been fixed in version 5, if it is still often stuck try playing the 'blitz' mode but in rapid games

**Comment by Veloruze** [comment]
> tried rapid mode but in the second move it bugged, there's a red highlight in the board and the bot won't move, it just spams like this
> ![image](https://user-images.githubusercontent.com/23275372/113282790-9d6fa980-9311-11eb-8e54-f33609accf09.png)

you can change line 196 with this
`waktu = random.uniform(1, 5)`

and line 200 with this
`waktu = random.uniform(1,7.5)`

you can modified with range time you want.

**Comment by tinwaninja** [comment]
> random.uniform(1,7.5)

thanks for the suggestion to use uniform as a random float number, I applied it for version 5
