### ISSUE TITLE
bot to stupid to play with a good player how to setting bot lv agility

### ISSUE THREAD

**Issue by idsystemku** [tinwaninja/Catur#5]
how to increase a bot lv to beat a good player bot to stupid when vs 2k elo player

**Comment by SuryaMaulana** [comment]
in config.ini and change the "depth" change the number between 1 and 20

**Comment by idsystemku** [comment]
How about a promote function i was send u an email

**Comment by SuryaMaulana** [comment]
not me

**Comment by tinwaninja** [comment]
I will rectify, accuracy 1-14
5 suggestions for normal
7 for ELO 2500
> 9 has a percentage frequency of more than 98%
